---

vmx1:
    hostname: 192.168.20.200
    groups:
        - junos_group
    data:
        host_name: "vmx1"
        ospf_interfaces:
            - "ge-0/0/1.0"
            - "ge-0/0/3.0"
            - "lo0.0"
vmx2:
    hostname: 192.168.20.201
    groups:
        - junos_group
    data:
        host_name: "vmx2"
vmx3:
    hostname: 192.168.20.202
    groups:
        - junos_group
    data:
        host_name: "vmx3"